# Generated by Django 3.1.6 on 2021-02-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteam',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='events.event'),
            preserve_default=False,
        ),
    ]
