# Generated by Django 3.1.6 on 2021-02-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210220_1913'),
        ('events', '0003_auto_20210220_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(through='events.EventPlayer', to='players.Player'),
        ),
    ]
