# Generated by Django 3.1.6 on 2021-02-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
    ]
